#!/usr/bin/env node
var debug = require('debug')('{app}');
var config = require('../config');
var app = require('../app');

app.set('port', process.env.PORT || config.port);

var server = app.listen(app.get('port'), function() {
  debug('Caminte listening on port ' + server.address().port);
  if(config.debug) console.log('Caminte server listening on port ' + server.address().port);
});